# Antibody

# where is antibody keeping its stuff?
ANTIBODY_HOME="$(antibody home)"

# omz plugins
plugins=(
  docker
  docker-compose
  gem
  git
  github
  heroku
  node
  npm
  osx
  themes
  z
)

# set the theme to something, or blank if you use a non omz theme
ZSH_THEME="cloud"

# tell omz where it lives
export ZSH="$ANTIBODY_HOME"/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh

# quit bugging me!
DISABLE_AUTO_UPDATE=true

source <(antibody init)
antibody bundle <~/.zsh_plugins

COMPLETION_WAITING_DOTS=true
ZSH_CUSTOM=$HOME/Projects/Github/dotfiles/home/zsh-custom
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_PATTERNS=('rm -rf *' 'fg=white,bold,bg=red')
setopt RM_STAR_WAIT

# load zmv
autoload zmv

# Bind some keys
bindkey "^[^[[C" forward-word
bindkey "^[^[[D" backward-word

# Init fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source own config files
source $HOME/.exports
source $HOME/.tokens
source $HOME/.aliases
source $HOME/.functions
source $HOME/.git-ls

# load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# load git-extras completion
source /usr/local/opt/git-extras/share/git-extras/git-extras-completion.zsh

# thefuck integration
eval $(thefuck --alias)

# load MOIA stuff
[ -f "$HOME/.moia" ] && source $HOME/.moia
