source $HOME/.antigen/antigen.zsh
antigen init $HOME/.antigenrc

COMPLETION_WAITING_DOTS="true"
ZSH_CUSTOM=$HOME/Projects/Github/dotfiles/home/zsh-custom
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_PATTERNS=('rm -rf *' 'fg=white,bold,bg=red')
setopt RM_STAR_WAIT

# load zmv
autoload zmv

# Bind some keys
bindkey "^[^[[C" forward-word
bindkey "^[^[[D" backward-word

# Init fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source own config files
source $HOME/.exports

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

source $HOME/.tokens
source $HOME/.aliases
source $HOME/.functions
source $HOME/.git-ls

# load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# load git-extras completion
source /usr/local/opt/git-extras/share/git-extras/git-extras-completion.zsh
